GCC=g++
SRCDIR=src
BINDIR=bin

BLASFLAGS=-DNDEBUG -DBOOST_UBLAS_NDEBUG
VECFLAGS=-ftree-vectorize -ftree-vectorizer-verbose=9 -ffast-math -fassociative-math -msse2
OMPFLAGS=-fopenmp

CHOLCSRCO=cholcO.cpp
CHOLCSRCC1=cholcC1.cpp
CHOLCSRCC2=cholcC2.cpp

CHOLCBINO=cholcO
CHOLCBINC1=cholcC1
CHOLCBINC2=cholcC2
CHOLVECCBINO=cholveccO
CHOLVECCBINC1=cholveccC1
CHOLVECCBINC2=cholveccC2


CHOLBOOSTSRCO=cholboostO.cpp
CHOLBOOSTSRCC=cholboostC.cpp

CHOLBOOSTBINO=cholboostO
CHOLBOOSTBINC=cholboostC
CHOLVECBOOSTBINO=cholvecboostO
CHOLVECBOOSTBINC=cholvecboostC


CHOLMTCSRC=cholmtc.cpp
CHOLMTCBIN=cholmtc

FOPT0=O0
FOPT1=O1
FOPT2=O2
FOPT3=O3
FOPT4=O4

all: cholcall cholveccall cholboostall cholvecboostall cholmtcall $(BINDIR)/converter $(BINDIR)/generator $(BINDIR)/validboost $(BINDIR)/frobboost $(BINDIR)/frobc $(BINDIR)/outputter

cholcall: cholc0 cholc1 cholc2 cholc3 cholc4

cholveccall: cholvecc0 cholvecc1 cholvecc2 cholvecc3 cholvecc4

cholboostall: cholboost0 cholboost1 cholboost2 cholboost3 cholboost4

cholvecboostall: cholvecboost0 cholvecboost1 cholvecboost2 cholvecboost3 cholvecboost4

cholmtcall: $(BINDIR)/$(CHOLMTCBIN)$(FOPT0) $(BINDIR)/$(CHOLMTCBIN)$(FOPT1) $(BINDIR)/$(CHOLMTCBIN)$(FOPT2) $(BINDIR)/$(CHOLMTCBIN)$(FOPT3) $(BINDIR)/$(CHOLMTCBIN)$(FOPT4)

cholc0: $(BINDIR)/$(CHOLCBINO)$(FOPT0) $(BINDIR)/$(CHOLCBINC1)$(FOPT0) $(BINDIR)/$(CHOLCBINC2)$(FOPT0)

cholc1: $(BINDIR)/$(CHOLCBINO)$(FOPT1) $(BINDIR)/$(CHOLCBINC1)$(FOPT1) $(BINDIR)/$(CHOLCBINC2)$(FOPT1)

cholc2: $(BINDIR)/$(CHOLCBINO)$(FOPT2) $(BINDIR)/$(CHOLCBINC1)$(FOPT2) $(BINDIR)/$(CHOLCBINC2)$(FOPT2)

cholc3: $(BINDIR)/$(CHOLCBINO)$(FOPT3) $(BINDIR)/$(CHOLCBINC1)$(FOPT3) $(BINDIR)/$(CHOLCBINC2)$(FOPT3)

cholc4: $(BINDIR)/$(CHOLCBINO)$(FOPT4) $(BINDIR)/$(CHOLCBINC1)$(FOPT4) $(BINDIR)/$(CHOLCBINC2)$(FOPT4)


cholvecc0: $(BINDIR)/$(CHOLVECCBINO)$(FOPT0) $(BINDIR)/$(CHOLVECCBINC1)$(FOPT0) $(BINDIR)/$(CHOLVECCBINC2)$(FOPT0)

cholvecc1: $(BINDIR)/$(CHOLVECCBINO)$(FOPT1) $(BINDIR)/$(CHOLVECCBINC1)$(FOPT1) $(BINDIR)/$(CHOLVECCBINC2)$(FOPT1)

cholvecc2: $(BINDIR)/$(CHOLVECCBINO)$(FOPT2) $(BINDIR)/$(CHOLVECCBINC1)$(FOPT2) $(BINDIR)/$(CHOLVECCBINC2)$(FOPT2)

cholvecc3: $(BINDIR)/$(CHOLVECCBINO)$(FOPT3) $(BINDIR)/$(CHOLVECCBINC1)$(FOPT3) $(BINDIR)/$(CHOLVECCBINC2)$(FOPT3)

cholvecc4: $(BINDIR)/$(CHOLVECCBINO)$(FOPT4) $(BINDIR)/$(CHOLVECCBINC1)$(FOPT4) $(BINDIR)/$(CHOLVECCBINC2)$(FOPT4)


cholboost0: $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT0) $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT0)

cholboost1: $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT1) $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT1)

cholboost2: $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT2) $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT2)

cholboost3: $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT3) $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT3)

cholboost4: $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT4) $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT4)


cholvecboost0: $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT0) $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT0)

cholvecboost1: $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT1) $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT1)

cholvecboost2: $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT2) $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT2)

cholvecboost3: $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT3) $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT3)

cholvecboost4: $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT4) $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT4)


#cholc0

$(BINDIR)/$(CHOLCBINO)$(FOPT0): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -std=c++11 $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLCBINO)$(FOPT0)

$(BINDIR)/$(CHOLCBINC1)$(FOPT0): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -std=c++11 $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLCBINC1)$(FOPT0)
	
$(BINDIR)/$(CHOLCBINC2)$(FOPT0): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -std=c++11 $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLCBINC2)$(FOPT0)
	
#cholc1

$(BINDIR)/$(CHOLCBINO)$(FOPT1): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -O1 -std=c++11 $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLCBINO)$(FOPT1)

$(BINDIR)/$(CHOLCBINC1)$(FOPT1): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -O1 -std=c++11 $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLCBINC1)$(FOPT1)
	
$(BINDIR)/$(CHOLCBINC2)$(FOPT1): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -O1 -std=c++11 $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLCBINC2)$(FOPT1)
	
#cholc2
	
$(BINDIR)/$(CHOLCBINO)$(FOPT2): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -O2 -std=c++11 $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLCBINO)$(FOPT2)

$(BINDIR)/$(CHOLCBINC1)$(FOPT2): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -O2 -std=c++11 $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLCBINC1)$(FOPT2)
	
$(BINDIR)/$(CHOLCBINC2)$(FOPT2): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -O2 -std=c++11 $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLCBINC2)$(FOPT2)

#cholc3

$(BINDIR)/$(CHOLCBINO)$(FOPT3): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -O3 -std=c++11 $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLCBINO)$(FOPT3)

$(BINDIR)/$(CHOLCBINC1)$(FOPT3): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -O3 -std=c++11 $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLCBINC1)$(FOPT3)
	
$(BINDIR)/$(CHOLCBINC2)$(FOPT3): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -O3 -std=c++11 $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLCBINC2)$(FOPT3)
	
#cholc4

$(BINDIR)/$(CHOLCBINO)$(FOPT4): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -Ofast -std=c++11 $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLCBINO)$(FOPT4)

$(BINDIR)/$(CHOLCBINC1)$(FOPT4): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -Ofast -std=c++11 $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLCBINC1)$(FOPT4)
	
$(BINDIR)/$(CHOLCBINC2)$(FOPT4): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -Ofast -std=c++11 $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLCBINC2)$(FOPT4)
	

#cholvecc0	
	
$(BINDIR)/$(CHOLVECCBINO)$(FOPT0): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLVECCBINO)$(FOPT0)
	
$(BINDIR)/$(CHOLVECCBINC1)$(FOPT0): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLVECCBINC1)$(FOPT0)
	
$(BINDIR)/$(CHOLVECCBINC2)$(FOPT0): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLVECCBINC2)$(FOPT0)
	
#cholvecc1	

$(BINDIR)/$(CHOLVECCBINO)$(FOPT1): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -O1 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLVECCBINO)$(FOPT1)
	
$(BINDIR)/$(CHOLVECCBINC1)$(FOPT1): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -O1 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLVECCBINC1)$(FOPT1)
	
$(BINDIR)/$(CHOLVECCBINC2)$(FOPT1): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -O1 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLVECCBINC2)$(FOPT1)
	
#cholvecc2

$(BINDIR)/$(CHOLVECCBINO)$(FOPT2): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -O2 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLVECCBINO)$(FOPT2)
	
$(BINDIR)/$(CHOLVECCBINC1)$(FOPT2): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -O2 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLVECCBINC1)$(FOPT2)
	
$(BINDIR)/$(CHOLVECCBINC2)$(FOPT2): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -O2 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLVECCBINC2)$(FOPT2)
	
#cholvecc3

$(BINDIR)/$(CHOLVECCBINO)$(FOPT3): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -O3 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLVECCBINO)$(FOPT3)
	
$(BINDIR)/$(CHOLVECCBINC1)$(FOPT3): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -O3 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLVECCBINC1)$(FOPT3)
	
$(BINDIR)/$(CHOLVECCBINC2)$(FOPT3): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -O3 $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLVECCBINC2)$(FOPT3)
	
#cholvecc4	

$(BINDIR)/$(CHOLVECCBINO)$(FOPT4): $(SRCDIR)/$(CHOLCSRCO)
	$(GCC) -Ofast $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCO) -o $(BINDIR)/$(CHOLVECCBINO)$(FOPT4)
	
$(BINDIR)/$(CHOLVECCBINC1)$(FOPT4): $(SRCDIR)/$(CHOLCSRCC1)
	$(GCC) -Ofast $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC1) -o $(BINDIR)/$(CHOLVECCBINC1)$(FOPT4)
	
$(BINDIR)/$(CHOLVECCBINC2)$(FOPT4): $(SRCDIR)/$(CHOLCSRCC2)
	$(GCC) -Ofast $(VECFLAGS) $(SRCDIR)/$(CHOLCSRCC2) -o $(BINDIR)/$(CHOLVECCBINC2)$(FOPT4)

#cholcboost0
	
$(BINDIR)/$(CHOLBOOSTBINO)$(FOPT0): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT0)

$(BINDIR)/$(CHOLBOOSTBINC)$(FOPT0): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT0)
	
#cholcboost1
	
$(BINDIR)/$(CHOLBOOSTBINO)$(FOPT1): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) -O1 $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT1)

$(BINDIR)/$(CHOLBOOSTBINC)$(FOPT1): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) -O1 $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT1)
	
#cholcboost2
	
$(BINDIR)/$(CHOLBOOSTBINO)$(FOPT2): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) -O2 $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT2)

$(BINDIR)/$(CHOLBOOSTBINC)$(FOPT2): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) -O2 $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT2)
	
#cholcboost3
	
$(BINDIR)/$(CHOLBOOSTBINO)$(FOPT3): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) -O3 $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT3)

$(BINDIR)/$(CHOLBOOSTBINC)$(FOPT3): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) -O3 $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT3)
	
#cholcboost4
	
$(BINDIR)/$(CHOLBOOSTBINO)$(FOPT4): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) -Ofast $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLBOOSTBINO)$(FOPT4)

$(BINDIR)/$(CHOLBOOSTBINC)$(FOPT4): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) -Ofast $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLBOOSTBINC)$(FOPT4)	

#cholcvecboost0
	
$(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT0): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT0)
	
$(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT0): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT0)
	
#cholcvecboost1
	
$(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT1): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) -O1 $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT1)
	
$(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT1): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) -O1 $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT1)
	
#cholcvecboost2
	
$(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT2): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) -O2 $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT2)
	
$(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT2): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) -O2 $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT2)
	
#cholcvecboost3
	
$(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT3): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) -O3 $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT3)
	
$(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT3): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) -O3 $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT3)
	
#cholcvecboost4
	
$(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT4): $(SRCDIR)/$(CHOLBOOSTSRCO)
	$(GCC) -Ofast $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCO) -o $(BINDIR)/$(CHOLVECBOOSTBINO)$(FOPT4)
	
$(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT4): $(SRCDIR)/$(CHOLBOOSTSRCC)
	$(GCC) -Ofast $(VECFLAGS) $(BLASFLAGS) $(SRCDIR)/$(CHOLBOOSTSRCC) -o $(BINDIR)/$(CHOLVECBOOSTBINC)$(FOPT4)
	
	
#cholmtc	

$(BINDIR)/$(CHOLMTCBIN)$(FOPT0): $(SRCDIR)/$(CHOLMTCSRC)
	$(GCC) $(OMPFLAGS) $(SRCDIR)/$(CHOLMTCSRC) -o $(BINDIR)/$(CHOLMTCBIN)$(FOPT0)
	
$(BINDIR)/$(CHOLMTCBIN)$(FOPT1): $(SRCDIR)/$(CHOLMTCSRC)
	$(GCC) -O1 $(OMPFLAGS) $(SRCDIR)/$(CHOLMTCSRC) -o $(BINDIR)/$(CHOLMTCBIN)$(FOPT1)

$(BINDIR)/$(CHOLMTCBIN)$(FOPT2): $(SRCDIR)/$(CHOLMTCSRC)
	$(GCC) -O2 $(OMPFLAGS) $(SRCDIR)/$(CHOLMTCSRC) -o $(BINDIR)/$(CHOLMTCBIN)$(FOPT2)

$(BINDIR)/$(CHOLMTCBIN)$(FOPT3): $(SRCDIR)/$(CHOLMTCSRC)
	$(GCC) -O3 $(OMPFLAGS) $(SRCDIR)/$(CHOLMTCSRC) -o $(BINDIR)/$(CHOLMTCBIN)$(FOPT3)

$(BINDIR)/$(CHOLMTCBIN)$(FOPT4): $(SRCDIR)/$(CHOLMTCSRC)
	$(GCC) -Ofast $(OMPFLAGS) $(SRCDIR)/$(CHOLMTCSRC) -o $(BINDIR)/$(CHOLMTCBIN)$(FOPT4)

#utilities	
	
$(BINDIR)/converter: $(SRCDIR)/converter.cpp
	$(GCC) -std=c++11 $(SRCDIR)/converter.cpp -o $(BINDIR)/converter

$(BINDIR)/generator: $(SRCDIR)/generator.cpp
	$(GCC) -std=c++11 $(SRCDIR)/generator.cpp -o $(BINDIR)/generator
	
$(BINDIR)/validator: $(SRCDIR)/validator.cpp
	$(GCC) $(SRCDIR)/validator.cpp -o $(BINDIR)/validator
	
$(BINDIR)/validboost: $(SRCDIR)/validboost.cpp
	$(GCC) $(SRCDIR)/validboost.cpp -o $(BINDIR)/validboost

$(BINDIR)/properer: $(SRCDIR)/properer.cpp
	$(GCC) $(SRCDIR)/properer.cpp -o $(BINDIR)/properer	
	
$(BINDIR)/frobboost: $(SRCDIR)/frobboost.cpp
	$(GCC) $(SRCDIR)/frobboost.cpp -o $(BINDIR)/frobboost	
	
$(BINDIR)/frobc: $(SRCDIR)/frobc.cpp
	$(GCC) $(SRCDIR)/frobc.cpp -o $(BINDIR)/frobc	
	
$(BINDIR)/outputter: $(SRCDIR)/outputter.cpp
	$(GCC) $(SRCDIR)/outputter.cpp -o $(BINDIR)/outputter	

.PHONY: clean all

clean:
	rm -f $(BINDIR)/*
	
cleancholc:
	rm -f $(BINDIR)/cholc*
	
cleancholboost:
	rm -f $(BINDIR)/cholboost*
	
cleancholmtc:
	rm -f $(BINDIR)/cholmtc*
	
cleancholmtboost:
	rm -f $(BINDIR)/cholmtboost*
